version: '3'
services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: anylistDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - "27017:27017"
    container_name: anylistMongo
    volumes:
      - ./mongo:/data/db
